'use strict';
const assert=require('node:assert/strict'), fs=require('node:fs'), os=require('node:os'), path=require('node:path'), crypto=require('node:crypto');
const {LocalAgentRuntime}=require('../src/local-agent-runtime');
const {LocalBrainRelay,crypt,decodeDocument}=require('../src/local-brain-relay');
const {LocalDataStore}=require('../src/local-data');
const {PairedConversationSync}=require('../src/paired-conversation-sync');
(async()=>{
  let quotaRequests=0;
  const quotaRelay=new LocalBrainRelay({projectId:'fixture',getState:async()=>({brainId:'brain',key:'key',session:{idToken:'fixture'}}),fetchImpl:async()=>{
    quotaRequests++;
    return {ok:false,status:429,json:async()=>[{error:{message:'Quota exceeded.',status:'RESOURCE_EXHAUSTED'}}]};
  }});
  await assert.rejects(quotaRelay.poll(),/Quota exceeded/);
  await quotaRelay.poll();
  await assert.rejects(quotaRelay.request('fixture', {idToken:'fixture'}),/quota exceeded/);
  assert.equal(quotaRequests,1,'quota failure must back off rather than hammering Firebase');
  const queries=[];
  const idleRelay=new LocalBrainRelay({projectId:'fixture',getState:async()=>({brainId:'brain',key:'key',session:{idToken:'fixture'}})});
  idleRelay.heartbeat=async()=>{};
  idleRelay.query=async(_brain,_session,collection,status)=>{queries.push({collection,status});return []};
  await idleRelay.poll();await idleRelay.poll();
  assert.equal(queries.filter(x=>x.collection==='commands').length,2,'one command query per poll');
  assert.equal(queries.filter(x=>x.collection==='pairings').length,1,'pairing checks must be throttled');
  const frames=[{message:{content:'Café '}},{message:{content:'works'}},{done:true,eval_count:2,message:{content:''}}];
  const bytes=Buffer.from(frames.map(x=>JSON.stringify(x)).join('\n')+'\n');
  const chunks=[];
  for(let i=0;i<bytes.length;i+=2) chunks.push(bytes.subarray(i,i+2));
  const updates=[];
  const runtime=new LocalAgentRuntime({fetchImpl:async(_url,options)=>{
    assert.equal(JSON.parse(options.body).stream,true);
    return {ok:true,body:(async function*(){yield* chunks;})()};
  }});
  const reply=await runtime.chat('test',[],[],null,text=>updates.push(text));
  assert.deepEqual(updates,['Café ','Café works']); assert.equal(reply.message.content,'Café works');
  const state={brainId:'brain',key:crypto.randomBytes(32),session:{idToken:'fixture'}};
  const id='stream-test',encrypted=crypt(state.key,`JBP1|brain|${id}|request`,Buffer.from(JSON.stringify({model:'fixture',messages:[{role:'user',content:'hello'}]})),null,true);
  const writes=[]; let finalWasPending=false;
  const relay=new LocalBrainRelay({projectId:'fixture',getState:async()=>state,runLocalAgent:async({onProgress})=>{
    await onProgress({stage:'Running on PC'}); await onProgress({text:'First token'});
    finalWasPending=writes.some(x=>x.status==='streaming') && !writes.some(x=>x.status==='done');
    return {content:'First token, final answer',usage:{completion_tokens:5}};
  }});
  relay.update=async(_doc,_session,values)=>{writes.push(values);return {};};
  await relay.run(state,{document:{name:'fixture/commands/'+id,updateTime:'v1'},data:{id,...encrypted}});
  assert.ok(finalWasPending,'encrypted partial must be written before inference completes');
  const partial=writes.find(x=>x.status==='streaming');
  assert.equal(crypt(state.key,`JBP1|brain|${id}|partial`,Buffer.from(partial.partialCiphertext,'base64url'),Buffer.from(partial.partialNonce,'base64url'),false),'First token');
  assert.equal(writes.at(-1).status,'done');
  assert.equal(relay.lastRun.partialUpdates,1);
  assert.ok(relay.lastRun.firstPartialAt <= relay.lastRun.completedAt);
  let releaseRun, heartbeats=0;
  const pendingRelay=new LocalBrainRelay({projectId:'fixture',getState:async()=>state});
  pendingRelay.heartbeat=async()=>{heartbeats++};
  pendingRelay.query=async(_brain,_session,collection,status)=>collection==='commands'&&status.includes('pending')?[{document:{name:'slow'},data:{status:'pending'}}]:[];
  pendingRelay.run=()=>new Promise(resolve=>{releaseRun=resolve});
  await pendingRelay.poll(); await pendingRelay.poll();
  assert.equal(heartbeats,2,'heartbeat must continue while inference is active');
  assert.equal(pendingRelay.active.size,1,'a running command must not be claimed twice');
  releaseRun(); await Promise.all(pendingRelay.active.values());
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'junction-paired-unit-'));
  const pc=new LocalDataStore(path.join(root,'pc')), phone=new LocalDataStore(path.join(root,'phone'));
  const pcSync=new PairedConversationSync(pc), phoneSync=new PairedConversationSync(phone);
  const conversation=phone.createConversation(); phone.addMessage(conversation.id,'USER','From phone','OWNER');
  pcSync.sync({records:phoneSync.records(),cursor:0});
  assert.equal(pc.conversation(conversation.id).messages[0].role,'user');
  pc.addMessage(conversation.id,'assistant','From PC','JUNCTION'); pc.renameConversation(conversation.id,'Both devices');
  phoneSync.sync({records:pcSync.records(),cursor:0});
  assert.equal(phone.conversation(conversation.id).messages.length,2);
  assert.equal(phone.conversation(conversation.id).title,'Both devices');
  const stale=phoneSync.records(); pc.deleteConversation(conversation.id);
  phoneSync.sync({records:pcSync.records(),cursor:0}); pcSync.sync({records:stale,cursor:0});
  assert.equal(pc.conversation(conversation.id),null); assert.equal(phone.conversation(conversation.id),null);
  const second=pc.createConversation(); pc.addMessage(second.id,'user','From desktop','OWNER');
  phoneSync.sync({records:pcSync.records(),cursor:0}); phone.deleteConversation(second.id);
  pcSync.sync({records:phoneSync.records(),cursor:0}); assert.equal(pc.conversation(second.id),null);
  const large=pc.createConversation(); for(let i=0;i<6;i++)pc.addMessage(large.id,'user','x'.repeat(15000),'OWNER');
  let cursor=0,count=0; do {const page=pcSync.sync({records:[],cursor});assert.ok(Buffer.byteLength(JSON.stringify(page.records))<=35000);count+=page.records.filter(x=>x.kind==='message'||(x.kind==='message_part'&&x.value.index===0)).length;cursor=page.nextCursor;}while(cursor);
  assert.equal(count,6);
  const oversized=pc.createConversation();
  const longText='Large multilingual message 😀 漢字\n'.repeat(2200);
  pc.addMessage(oversized.id,'assistant',longText,'JUNCTION');
  cursor=0;
  do {
    const page=pcSync.sync({records:[],cursor});
    assert.ok(Buffer.byteLength(JSON.stringify(page.records))<=35000);
    phoneSync.sync({records:page.records,cursor:0});
    cursor=page.nextCursor;
  } while(cursor);
  assert.equal(phone.conversation(oversized.id).messages[0].content,longText);
  console.log('Streaming (UTF-8, encrypted partial before final), paired bidirectional messages/rename/delete, stale deletion, pagination passed.');
})().catch(error=>{console.error(error);process.exitCode=1;});
