"use strict";
const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");

class LocalDataStore {
  constructor(directory) { this.directory = directory; this.file = path.join(directory, "junction-local.json"); this.state = this.load(); }
  load() { try { const parsed=JSON.parse(fs.readFileSync(this.file,"utf8")),state={...this.empty(),...parsed};if(!parsed.syncOutbox){state.syncOutbox={conversations:state.conversations.map(x=>x.id),messages:state.conversations.flatMap(x=>(x.messages||[]).map(m=>`${x.id}/${m.id}`)),memories:state.memories.map(x=>x.id),conversationTombstones:state.conversationTombstones.map(x=>x.id),memoryTombstones:state.memoryTombstones.map(x=>x.id)}}return state; } catch { return this.empty(); } }
  empty() { return { conversations: [], conversationTombstones: [], memories: [], memoryTombstones: [], usage: [], provider: { id: "", model: "", baseUrl: "" }, syncOutbox:{conversations:[],messages:[],memories:[],conversationTombstones:[],memoryTombstones:[]} }; }
  save() { fs.mkdirSync(this.directory, { recursive: true }); const temp = `${this.file}.tmp`; fs.writeFileSync(temp, JSON.stringify(this.state, null, 2), { mode: 0o600 }); fs.renameSync(temp, this.file); }
  conversations() { return this.state.conversations.map(({ messages, ...item }) => ({ ...item, messageCount: messages.length })).sort((a,b) => b.updatedAt-a.updatedAt); }
  conversation(id) { return this.state.conversations.find(item => item.id === id) || null; }
  queue(kind,id){const values=this.state.syncOutbox[kind];if(!values.includes(id))values.push(id)}
  createConversation() { const now=Date.now(); const item={ id:crypto.randomUUID(), title:"New conversation", createdAt:now, updatedAt:now, messages:[] }; this.state.conversations.push(item);this.queue("conversations",item.id); this.save(); return item; }
  addMessage(id, role, content, provenance) { const item=this.conversation(id); if(!item) throw new Error("Conversation not found."); const message={ id:crypto.randomUUID(), role, content, provenance, createdAt:Date.now() }; item.messages.push(message); item.updatedAt=message.createdAt; if(role==="user"&&item.title==="New conversation") item.title=content.trim().slice(0,60)||item.title;this.queue("conversations",id);this.queue("messages",`${id}/${message.id}`); this.save(); return message; }
  renameConversation(id, title) { const item=this.conversation(id); if(!item) throw new Error("Conversation not found."); const clean=String(title||"").trim().slice(0,80); if(!clean) throw new Error("Conversation title cannot be blank."); item.title=clean; item.updatedAt=Date.now();this.queue("conversations",id); this.save(); return item; }
  deleteConversation(id) { const item=this.conversation(id); if(!item) throw new Error("Conversation not found."); this.state.conversations=this.state.conversations.filter(value=>value.id!==id); this.state.conversationTombstones=this.state.conversationTombstones||[]; this.state.conversationTombstones.push({id,deletedAt:Date.now(),createdAt:item.createdAt,updatedAt:Date.now(),title:item.title,createdByDeviceId:item.createdByDeviceId});this.state.syncOutbox.conversations=this.state.syncOutbox.conversations.filter(x=>x!==id);this.state.syncOutbox.messages=this.state.syncOutbox.messages.filter(x=>!x.startsWith(`${id}/`));this.queue("conversationTombstones",id); this.save(); }
  memories() { return [...this.state.memories].sort((a,b)=>b.createdAt-a.createdAt); }
  addMemory(content, category="other") { if(!content.trim()) throw new Error("Memory cannot be blank."); if(this.state.memories.length>=200) throw new Error("Memory is at its 200-fact limit."); const item={ id:crypto.randomUUID(), content:content.trim(), category:category.trim()||"other", createdAt:Date.now(), provenance:"OWNER", sourceRef:"owner:windows-settings" }; this.state.memories.push(item);this.queue("memories",item.id); this.save(); return item; }
  deleteMemory(id) { const item=this.state.memories.find(value=>value.id===id); if(!item)return; this.state.memories=this.state.memories.filter(value=>value.id!==id); this.state.memoryTombstones=this.state.memoryTombstones||[]; this.state.memoryTombstones.push({id,deletedAt:Date.now(),...item});this.state.syncOutbox.memories=this.state.syncOutbox.memories.filter(x=>x!==id);this.queue("memoryTombstones",id); this.save(); }
  sharedSnapshot() { const out=this.state.syncOutbox;return {conversations:this.state.conversations.filter(c=>out.conversations.includes(c.id)||c.messages.some(m=>out.messages.includes(`${c.id}/${m.id}`))).map(c=>({...c,messages:c.messages.filter(m=>out.messages.includes(`${c.id}/${m.id}`))})),conversationTombstones:(this.state.conversationTombstones||[]).filter(x=>out.conversationTombstones.includes(x.id)),memories:this.state.memories.filter(x=>out.memories.includes(x.id)),memoryTombstones:(this.state.memoryTombstones||[]).filter(x=>out.memoryTombstones.includes(x.id))}; }
  markSharedPublished(kind,id){this.state.syncOutbox[kind]=this.state.syncOutbox[kind].filter(x=>x!==id);this.save()}
  pendingSharedCount(){return Object.values(this.state.syncOutbox).reduce((sum,values)=>sum+values.length,0)}
  mergeSharedConversation(remote,messages) { const tombstone=(this.state.conversationTombstones||[]).find(x=>x.id===remote.id); if(remote.deletedAt||tombstone){if(remote.deletedAt){if(!tombstone)this.state.conversationTombstones.push({...remote,id:remote.id,deletedAt:remote.deletedAt});this.state.conversations=this.state.conversations.filter(x=>x.id!==remote.id);this.state.syncOutbox.conversations=this.state.syncOutbox.conversations.filter(x=>x!==remote.id);this.state.syncOutbox.messages=this.state.syncOutbox.messages.filter(x=>!x.startsWith(`${remote.id}/`));this.state.syncOutbox.conversationTombstones=this.state.syncOutbox.conversationTombstones.filter(x=>x!==remote.id)}this.save();return}let local=this.conversation(remote.id);if(!local){local={id:remote.id,title:remote.title||"Shared conversation",createdAt:remote.createdAt,updatedAt:remote.updatedAt,createdByDeviceId:remote.createdByDeviceId,messages:[]};this.state.conversations.push(local)}else if(Number(remote.updatedAt)>Number(local.updatedAt)){local.title=remote.title||local.title;local.updatedAt=remote.updatedAt;local.createdByDeviceId=remote.createdByDeviceId||local.createdByDeviceId}const ids=new Set(local.messages.map(x=>x.id));for(const message of messages){if(!ids.has(message.id)&&['OWNER','JUNCTION','UNTRUSTED'].includes(message.provenance)){local.messages.push(message);ids.add(message.id)}}local.messages.sort((a,b)=>a.createdAt-b.createdAt);this.save() }
  mergeSharedMemory(remote) { const tombstone=(this.state.memoryTombstones||[]).find(x=>x.id===remote.id);if(remote.deletedAt||tombstone){this.state.memories=this.state.memories.filter(x=>x.id!==remote.id);if(remote.deletedAt){if(!tombstone)this.state.memoryTombstones.push(remote);this.state.syncOutbox.memories=this.state.syncOutbox.memories.filter(x=>x!==remote.id);this.state.syncOutbox.memoryTombstones=this.state.syncOutbox.memoryTombstones.filter(x=>x!==remote.id)}this.save();return}if(remote.provenance==='OWNER'&&!this.state.memories.some(x=>x.id===remote.id)&&this.state.memories.length<200){this.state.memories.push(remote);this.save()} }
  provider() { return { ...this.state.provider }; }
  setProvider(value) { const id=String(value.id||""); if(id&&!['codex','openai','anthropic','deepseek','groq','custom'].includes(id)) throw new Error("Unsupported provider."); this.state.provider={ id, model:String(value.model||"").slice(0,200), baseUrl:String(value.baseUrl||"").slice(0,500) }; this.save(); return this.provider(); }
  usage() { return [...(this.state.usage||[])].sort((a,b)=>b.createdAt-a.createdAt).slice(0,200); }
  addUsage(value) { this.state.usage=this.state.usage||[]; this.state.usage.push({ id:crypto.randomUUID(), createdAt:Date.now(), ...value }); if(this.state.usage.length>500)this.state.usage=this.state.usage.slice(-500); this.save(); }
}
module.exports={ LocalDataStore };
