package com.splinch.junction.update

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.OkHttpClient
import okhttp3.Request
import org.json.JSONObject

data class UpdateInfo(
    val version: String,
    val versionCode: Int,
    val url: String,
    val apkUrl: String? = null,
    val sha256Url: String? = null
)

/**
 * Junction ships exactly one APK: one URL, one signing key, rebuilt on every push to
 * `main`. [MANIFEST_URL] is generated by the same CI job that publishes that APK, so it
 * always describes the precise bytes the download button is serving right now.
 *
 * This deliberately does not read GitHub Releases. Releases are built from tags by a
 * different workflow and signed with the *release* key, so an APK from there can never
 * install over a button-installed build -- Android rejects the signature mismatch and the
 * only way through is an uninstall, which destroys API keys, chat history and memory.
 * Offering such an "update" was the bug this replaces.
 */
class UpdateChecker(
    private val httpClient: OkHttpClient = OkHttpClient()
) {
    /**
     * Compares [currentVersionCode] against the published build. Version *codes* are the
     * comparison, not version names: `versionName` is a hand-edited marketing string that
     * stays "0.5.0" across hundreds of builds, so comparing it meant no published build
     * ever looked newer than the installed one.
     */
    suspend fun checkForUpdate(currentVersionCode: Int): UpdateInfo? = withContext(Dispatchers.IO) {
        runCatching {
            httpClient.newCall(Request.Builder().url(MANIFEST_URL).get().build()).execute().use { response ->
                if (!response.isSuccessful) return@use null
                val json = JSONObject(response.body?.string() ?: return@use null)
                val versionCode = json.optInt("versionCode", 0)
                if (versionCode <= currentVersionCode) return@use null
                UpdateInfo(
                    version = json.optString("versionName").trim().ifBlank { "build $versionCode" },
                    versionCode = versionCode,
                    url = json.optString("pageUrl").trim().ifBlank { DOWNLOAD_PAGE_URL },
                    apkUrl = json.optString("apkUrl").trim().takeIf { it.startsWith("https://") },
                    sha256Url = json.optString("sha256Url").trim().takeIf { it.startsWith("https://") }
                )
            }
        }.getOrNull()
    }

    companion object {
        const val MANIFEST_URL = "https://splinchgit.github.io/Junction/latest.json"
        const val DOWNLOAD_PAGE_URL = "https://splinchgit.github.io/Junction/"
    }
}
