"use strict";
(() => {
 const section=document.getElementById('view-projects');
 const area=document.createElement('div');area.className='foreman-area';
 area.innerHTML='<article class="panel"><h2>Persistent tasks</h2><p>Work runs only after Start or Resume, while Junction is open. Pause, Stop and Quit retain progress. Opening Junction never starts work.</p><form id="foreman-create"><label>Project name<input name="name" required maxlength="80" placeholder="Civlets"></label><label>Repository folder<input name="repoPath" required placeholder="Choose the existing project folder"></label><label>Owner objective<textarea name="objective" required maxlength="12000" rows="3"></textarea></label><label>First task<input name="title" required maxlength="240" placeholder="Validate the existing build and tests"></label><label>Acceptance criteria<textarea name="acceptance" required maxlength="4000" rows="2"></textarea></label><label>Executor<select name="kind"><option value="verify">Junction — run verification</option><option value="codex">Codex — engineering task</option></select></label><label>Verification profile<select name="profile"><option value="civlets">Civlets / Godot</option><option value="node">Node test runner</option><option value="custom">Custom command list</option></select></label><label id="foreman-checks-label">Verification commands (JSON argv; project-relative working directories)<textarea name="checks" rows="3">[{"command":["node","--test","--experimental-test-isolation=none"],"cwd":"."}]</textarea></label><button class="primary" type="submit">Save project — do not start</button></form><p id="foreman-error" role="status"></p></article><div id="foreman-projects"></div>';
 section.querySelector('header').after(area);
 const list=area.querySelector('#foreman-projects'),error=area.querySelector('#foreman-error'),form=area.querySelector('form');let pending=false;
 const element=(tag,value)=>{const e=document.createElement(tag);e.textContent=value;return e;};
 const call=async(fn)=>{try{error.textContent='';await fn();}catch(e){error.textContent=e.message;}finally{await refresh();}};
 const button=(label,fn)=>{const b=element('button',label);b.className='secondary';b.onclick=()=>call(fn);return b;};
 form.onsubmit=e=>{e.preventDefault();call(async()=>{const v=new FormData(form);let verification;if(v.get('profile')==='civlets')verification=['vertical_slice_smoke_test','autonomy_simulation_test','old_ones_coordination_test','development_test'].map(n=>({command:['godot','--headless','--path','.','--script',`res://tests/${n}.gd`],cwd:'pc_godot',protectedPaths:['tests','project.godot']}));else if(v.get('profile')==='node')verification=[{command:['node','--test','--experimental-test-isolation=none'],cwd:'.',protectedPaths:['test','tests','__tests__','package.json','package-lock.json']}];else verification=JSON.parse(v.get('checks'));await window.junction.foreman('project.register',{name:v.get('name'),repoPath:v.get('repoPath'),objective:v.get('objective'),verification,tasks:[{title:v.get('title'),acceptance:v.get('acceptance'),kind:v.get('kind')}]});error.textContent='Saved. Select Start when ready.';});};
 async function refresh(){if(pending)return;pending=true;try{
  const {projects}=await window.junction.foreman('project.list');list.replaceChildren();
  if(!projects.length)list.append(element('p','No projects registered. Save an objective and task to begin.'));
  for(const row of projects){const {project:p}=await window.junction.foreman('project.get',{id:row.id});const card=element('article','');card.className='delegation-card';card.append(element('h3',`${p.name} · ${p.status.replaceAll('_',' ')}`),element('p',p.objective),element('p',p.nextAction));
   if(p.retryAt)card.append(element('p',`Codex retry: ${new Date(p.retryAt).toLocaleString()}${p.status==='PAUSED'?' (requires Resume)':''}`));
   const controls=element('div','');controls.className='delegation-actions';const active=['RUNNING','VERIFYING','WAITING_CODEX'].includes(p.status);
   for(const a of active?['pause','stop']:p.status==='COMPLETED'?[]:[p.status==='DRAFT'?'start':'resume','stop'])controls.append(button(a[0].toUpperCase()+a.slice(1),()=>window.junction.foreman('task.control',{id:p.id,revision:p.revision,action:a})));
   card.append(controls);
   for(const t of p.tasks){const d=element('details','');d.append(element('summary',`${t.title} · ${t.kind==='verify'?'Junction':'Codex'} · ${t.status}`),element('p',t.acceptance));if(t.lastAttempt)d.append(element('pre',JSON.stringify(t.lastAttempt,null,2)));card.append(d);}
   card.append(element('p',p.handoff));if(p.worktree)card.append(element('p',`Preserved workspace: ${p.worktree}`));
   if(!active&&p.verifiedSha){card.append(button('Review verified diff',async()=>{const r=await window.junction.foreman('task.review',{id:p.id,revision:p.revision});alert(`${r.summary}\n${r.patch}\nCommit: ${r.headSha}\nDiff hash: ${r.diffHash}`);}));card.append(button('Apply reviewed changes to original',async()=>{if(confirm('Apply the exact reviewed changes to the original checkout? It must be clean and match the original baseline. Changes will be staged for your inspection.')){const r=await window.junction.foreman('task.apply',{id:p.id,revision:p.revision});alert(r.summary);}}));}
   if(!active){const add=document.createElement('form');const title=document.createElement('input');title.placeholder='Next task within this objective';title.required=true;const acceptance=document.createElement('input');acceptance.placeholder='Acceptance criteria';acceptance.required=true;const submit=element('button','Queue Codex task');submit.type='submit';add.append(title,acceptance,submit);add.onsubmit=e=>{e.preventDefault();call(()=>window.junction.foreman('task.enqueue',{id:p.id,revision:p.revision,title:title.value,acceptance:acceptance.value,kind:'codex'}));};card.append(add);}
   card.append(button('Show activity log',async()=>{let after=0,lines=[];for(let page=0;page<20;page++){const {events}=await window.junction.foreman('project.get',{id:p.id,after});if(!events.length)break;lines.push(...events.map(e=>`${new Date(e.at).toLocaleString()} ${e.kind}: ${e.detail}`));after=events.at(-1).seq;}const log=element('pre',lines.join('\n'));card.append(log);}));list.append(card);
  }
 }catch(e){error.textContent=e.message;}finally{pending=false;}}
 document.querySelector('[data-view="projects"]').addEventListener('click',refresh);
 setInterval(()=>{if(section.classList.contains('active')&&!area.contains(document.activeElement))refresh();},3000);refresh();
})();
