"use strict";
(() => {
 const section=document.getElementById('view-projects'),header=section.querySelector('header');header.querySelector('small').textContent='LIVE WORK · LOCAL';header.querySelector('h1').textContent='Work Activity';header.querySelector('mark').textContent='Owner controlled';
 const area=document.createElement('div');area.className='foreman-area';area.innerHTML='<article class="panel foreman-explainer"><h2>Tell Junction what to work on</h2><p>Use Chat normally. Name a file, folder or repository in your request; that message starts the work and keeps its context. Junction never copies a project into its own repository.</p><p>Example: <code>Work on Civlets and fix the failing build</code></p><p id="foreman-error" role="status"></p></article><div id="foreman-projects"></div>';section.querySelector('.projects-grid')?.remove();header.after(area);
 const list=area.querySelector('#foreman-projects'),error=area.querySelector('#foreman-error');let pending=false;
 const element=(tag,value,className='')=>{const e=document.createElement(tag);e.textContent=value;if(className)e.className=className;return e;};
 const call=async fn=>{try{error.textContent='';await fn();}catch(e){error.textContent=e.message;}finally{await refresh();}};
 const stopButton=p=>{const b=element('button','Stop work','danger');b.onclick=()=>call(()=>window.junction.foreman('task.control',{id:p.id,revision:p.revision,action:'stop'}));return b;};
 function statusText(p){if(['RUNNING','VERIFYING'].includes(p.status))return 'Junction is working';if(p.status==='WAITING_CODEX')return 'Waiting for legitimate Codex availability';if(p.status==='BLOCKED')return 'Blocked — tell Junction how to proceed in Chat';if(p.status==='PAUSED')return 'Paused when Junction closed — say “continue” in Chat';if(p.status==='STOPPED')return 'Stopped by owner';if(p.status==='COMPLETED')return 'Current queue complete';return 'Waiting for an instruction in Chat';}
 async function refresh(){if(pending)return;pending=true;try{const {projects}=await window.junction.foreman('project.list');list.replaceChildren();if(!projects.length)list.append(element('p','No active work yet. Give Junction a development instruction in Chat.'));
  for(const row of projects){const {project:p}=await window.junction.foreman('project.get',{id:row.id});const card=element('article','');card.className='delegation-card';card.append(element('h3',`${p.name} · ${p.status.replaceAll('_',' ')}`),element('strong',statusText(p)),element('p',p.repoPath||''),element('p',p.objective));
   const active=['RUNNING','VERIFYING','WAITING_CODEX'].includes(p.status);if(active){const actions=element('div','');actions.className='delegation-actions';actions.append(stopButton(p));card.append(actions);}if(p.retryAt)card.append(element('p',`Next permitted Codex retry: ${new Date(p.retryAt).toLocaleString()}`));
   for(const t of p.tasks.slice(-8)){const d=element('details','');d.append(element('summary',`${t.title} · ${t.kind==='verify'?'Junction':'Codex'} · ${t.status}`),element('p',t.acceptance));if(t.lastAttempt)d.append(element('pre',JSON.stringify(t.lastAttempt,null,2)));card.append(d);}if(p.handoff)card.append(element('p',`Latest: ${p.handoff}`));if(p.lastBackup)card.append(element('p',`Rollback checkpoint: ${p.lastBackup}`));
   const logButton=element('button','Show activity log','secondary');logButton.onclick=()=>call(async()=>{let after=0,lines=[];for(let page=0;page<20;page++){const {events}=await window.junction.foreman('project.get',{id:p.id,after});if(!events.length)break;lines.push(...events.map(e=>`${new Date(e.at).toLocaleString()} ${e.kind}: ${e.detail}`));after=events.at(-1).seq;}card.append(element('pre',lines.join('\n')));});card.append(logButton);list.append(card);}
 }catch(e){error.textContent=e.message;}finally{pending=false;}}
 const chat=document.querySelector('#view-chat .conversation'),banner=element('div','');banner.id='work-status';banner.className='work-status hidden';chat.prepend(banner);
 async function refreshBanner(){try{const {projects}=await window.junction.foreman('project.list'),p=projects.find(item=>['RUNNING','VERIFYING','WAITING_CODEX'].includes(item.status));if(!p){banner.classList.add('hidden');banner.replaceChildren();return;}banner.classList.remove('hidden');banner.replaceChildren(element('span',`${p.name}: ${statusText(p)}`));banner.append(stopButton(p));}catch{}}
 document.querySelector('[data-view="projects"]').addEventListener('click',refresh);setInterval(()=>{refreshBanner();if(section.classList.contains('active'))refresh();},3000);refresh();refreshBanner();
})();
