"use strict";
let activeConversationId=null;
const byId=id=>document.getElementById(id);
async function loadThreads(selectFirst=false){const threads=await window.junction.conversations(),list=byId("thread-list");list.replaceChildren(...threads.map((item,index)=>{const row=document.createElement("div");row.className="thread-row";const select=document.createElement("button");select.className=`thread thread-select${item.id===activeConversationId?" active":""}`;select.textContent=item.title;select.title=item.title;select.setAttribute("aria-current",item.id===activeConversationId?"true":"false");select.onclick=()=>openConversation(item.id);select.onkeydown=event=>{if(event.key==="F2"){event.preventDefault();startRename(row,item)}else if(event.key==="Delete"){event.preventDefault();deleteThread(item)}else if(event.key==="ArrowDown"||event.key==="ArrowUp"){event.preventDefault();const buttons=[...list.querySelectorAll(".thread-select")],next=(buttons.indexOf(select)+(event.key==="ArrowDown"?1:-1)+buttons.length)%buttons.length;buttons[next]?.focus()}};const actions=document.createElement("div");actions.className="thread-actions";const rename=document.createElement("button");rename.textContent="✎";rename.title="Rename conversation (F2)";rename.setAttribute("aria-label",`Rename ${item.title}`);rename.onclick=()=>startRename(row,item);const remove=document.createElement("button");remove.textContent="×";remove.title="Delete conversation (Delete)";remove.setAttribute("aria-label",`Delete ${item.title}`);remove.onclick=()=>deleteThread(item);actions.append(rename,remove);row.append(select,actions);return row}));if(selectFirst&&!activeConversationId&&threads[0])await openConversation(threads[0].id)}
function startRename(row,item){const input=document.createElement("input");let finishing=false;input.className="thread-rename";input.value=item.title;input.maxLength=80;const finish=async save=>{if(finishing)return;finishing=true;if(save&&input.value.trim()){await window.junction.renameConversation({id:item.id,title:input.value});await loadThreads();document.querySelector(`[aria-current="true"]`)?.focus()}else await loadThreads()};input.onkeydown=event=>{if(event.key==="Enter"){event.preventDefault();finish(true)}else if(event.key==="Escape"){event.preventDefault();finish(false)}};input.onblur=()=>finish(Boolean(input.value.trim()));row.replaceChildren(input);input.focus();input.select()}
async function deleteThread(item){if(!window.confirm(`Delete “${item.title}” from this PC? This cannot be undone.`))return;await window.junction.deleteConversation(item.id);if(activeConversationId===item.id)activeConversationId=null;const remaining=await window.junction.conversations();if(remaining[0])await openConversation(remaining[0].id);else{renderMessages([]);await loadThreads()}}
async function openConversation(id){activeConversationId=id;const item=await window.junction.conversation(id);renderMessages(item?.messages||[]);await loadThreads()}
function renderMessages(messages){const target=byId("messages");if(!messages.length){target.innerHTML='<div class="chat-home"><div class="orb"><b></b><b></b><b></b></div><h2>What can I help you with?</h2><p>This conversation is local-first. If account sync is enabled, compact changes reconcile automatically.</p></div>';return}target.replaceChildren(...messages.map(value=>{const node=document.createElement("div");node.className=`message ${value.role}`;const role=document.createElement("div");role.className="role";role.textContent=value.role==="user"?"YOU":"JUNCTION";const bubble=document.createElement("div");bubble.className="bubble";bubble.textContent=value.content;const provenance=document.createElement("div");provenance.className="provenance";provenance.textContent=`${value.provenance} · ${new Date(value.createdAt).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}`;node.append(role,bubble,provenance);return node}));target.scrollTop=target.scrollHeight}
async function newChat(){const item=await window.junction.newConversation();activeConversationId=item.id;await openConversation(item.id);byId("message-input").focus()}
async function send(){const input=byId("message-input"),content=input.value.trim();if(!content)return;if(!activeConversationId)await newChat();input.value="";byId("send-message").disabled=true;const existing=await window.junction.conversation(activeConversationId);renderMessages([...(existing?.messages||[]),{role:"user",content,provenance:"OWNER",createdAt:Date.now()}]);try{const result=await window.junction.sendMessage({conversationId:activeConversationId,content,context:contextSnapshot});activeConversationId=result.conversationId;contextSnapshot=null;byId("context-chip").classList.add("hidden");await openConversation(activeConversationId)}catch(error){message("error",error.message);await openConversation(activeConversationId)}finally{byId("send-message").disabled=false;input.focus()}}
async function loadProvider(){const value=await window.junction.provider();byId("provider-id").value=value.id;byId("provider-model").value=value.model;byId("provider-url").value=value.baseUrl;byId("provider-status").textContent=value.keyPresent?"Encrypted key present":"No key on this PC"}
async function loadMemories(){const values=await window.junction.memories();const list=byId("memory-list");list.replaceChildren(...values.map(value=>{const row=document.createElement("div");row.className="memory-row";const category=document.createElement("span");category.textContent=value.category;const content=document.createElement("span");content.textContent=value.content;const remove=document.createElement("button");remove.textContent="Forget";remove.onclick=async()=>{await window.junction.deleteMemory(value.id);await loadMemories()};row.append(category,content,remove);return row}))}
const threadPane=document.querySelector(".threads"),threadLabel=threadPane.querySelector(":scope > strong"),threadList=byId("thread-list"),drawerHead=document.createElement("div"),drawerNew=document.createElement("button");drawerHead.className="drawer-head";drawerHead.append(threadLabel);drawerNew.textContent="＋ New";drawerNew.onclick=newChat;drawerHead.append(drawerNew);threadPane.replaceChildren(drawerHead,threadList);threadPane.id="chat-drawer";const drawerToggle=document.createElement("button");drawerToggle.id="drawer-toggle";drawerToggle.className="square drawer-toggle";drawerToggle.textContent="☰";drawerToggle.title="Collapse conversation drawer (Ctrl+B)";drawerToggle.setAttribute("aria-controls","chat-drawer");drawerToggle.setAttribute("aria-expanded","true");byId("new-chat").before(drawerToggle);function toggleDrawer(force){const layout=document.querySelector(".chat-layout"),collapsed=force??!layout.classList.contains("drawer-collapsed");layout.classList.toggle("drawer-collapsed",collapsed);drawerToggle.setAttribute("aria-expanded",String(!collapsed));threadPane.setAttribute("aria-hidden",String(collapsed));drawerToggle.title=`${collapsed?"Expand":"Collapse"} conversation drawer (Ctrl+B)`;if(!collapsed)setTimeout(()=>threadPane.querySelector(".thread-select")?.focus(),210)}drawerToggle.onclick=()=>toggleDrawer();
byId("new-chat").onclick=newChat;byId("send-message").onclick=send;byId("message-input").addEventListener("keydown",event=>{if(event.key==="Enter"&&!event.shiftKey){event.preventDefault();send()}});
byId("save-provider").onclick=()=>action(async()=>{await window.junction.setProvider({id:byId("provider-id").value,model:byId("provider-model").value.trim(),baseUrl:byId("provider-url").value.trim(),apiKey:byId("provider-key").value.trim()});byId("provider-key").value="";await loadProvider();message("toast","Provider settings saved on this PC.")});
byId("add-memory").onclick=()=>action(async()=>{await window.junction.addMemory({category:byId("memory-category").value,content:byId("memory-content").value});byId("memory-content").value="";await loadMemories();message("toast","Remembered locally.")});
document.querySelector('[data-view="settings"]').addEventListener("click",()=>{loadProvider();loadMemories()});
document.addEventListener("keydown",event=>{const views=["chat","feed","audit","context","settings"];if(event.ctrlKey&&/^[1-5]$/.test(event.key)){event.preventDefault();showView(views[Number(event.key)-1])}else if(event.ctrlKey&&event.key.toLowerCase()==="n"){event.preventDefault();showView("chat");newChat()}else if(event.ctrlKey&&event.key.toLowerCase()==="b"){event.preventDefault();showView("chat");toggleDrawer()}else if(event.key==="Escape"&&document.querySelector("#view-chat.active")&&!document.querySelector(".chat-layout").classList.contains("drawer-collapsed")){toggleDrawer(true);drawerToggle.focus()}else if(event.key==="/"&&!event.ctrlKey&&!event.metaKey&&document.activeElement?.tagName!=="INPUT"&&document.activeElement?.tagName!=="TEXTAREA"){event.preventDefault();showView("chat");byId("message-input").focus()}});
loadThreads(true);loadProvider();loadMemories();
