"use strict";
const product=id=>document.getElementById(id);
let catalog=[];
function settingLabel(text,before){const label=document.createElement("div");label.className="settings-group-label";label.textContent=text;before.before(label)}
const settingsCards=[...document.querySelectorAll(".settings > article")];if(settingsCards[0])settingLabel("ACCOUNT & SYNC",settingsCards[0]);const providerCard=document.querySelector(".provider-card"),memoryCard=document.querySelector(".memory-card");if(providerCard)settingLabel("AI & MODELS",providerCard);if(memoryCard)settingLabel("PERSONALISATION",memoryCard);if(settingsCards.at(-1))settingLabel("PRIVACY & PERMISSIONS",settingsCards.at(-1));
const modelSelect=product("provider-model"),modelOptions=document.createElement("datalist");modelOptions.id="model-options";modelSelect.setAttribute("list","model-options");modelSelect.after(modelOptions);
async function loadCatalog(){catalog=await window.junction.modelCatalog();const provider=product("provider-id");provider.replaceChildren(new Option("Choose provider",""),...catalog.map(item=>new Option(`${item.name} · ${item.tag}`,item.id)));const current=await window.junction.provider();provider.value=current.id;renderModels(current.id,current.model);product("provider-url").value=current.baseUrl;product("provider-status").textContent=current.keyPresent?"Encrypted key present":"No key on this PC";updateSetup(current)}
function renderModels(providerId,current=""){const definition=catalog.find(item=>item.id===providerId);modelOptions.replaceChildren(...(definition?.models||[]).map(model=>{const option=document.createElement("option");option.value=model.id;option.label=`${model.name} · ${model.tier}`;return option}));modelSelect.value=current||definition?.models?.[0]?.id||"";modelSelect.placeholder=definition?.models.length?"Choose or enter model":"Enter custom model";const selected=definition?.models?.find(model=>model.id===modelSelect.value);setModelDetail(selected)}
function setModelDetail(model){let detail=document.querySelector(".model-detail");if(!detail){detail=document.createElement("div");detail.className="model-detail";modelSelect.after(detail)}detail.textContent=model?`Estimated catalog rates: $${model.input}/M input · $${model.output}/M output`:"Custom endpoint pricing is not known to Junction."}
product("provider-id").addEventListener("change",event=>{renderModels(event.target.value);product("provider-url").disabled=event.target.value!=="custom"});modelSelect.addEventListener("change",()=>setModelDetail(catalog.flatMap(p=>p.models).find(m=>m.id===modelSelect.value)));
function updateSetup(provider){let banner=document.querySelector(".setup-banner");if(provider.id&&provider.keyPresent){banner?.remove();return}if(!banner){banner=document.createElement("div");banner.className="setup-banner";const copy=document.createElement("div"),strong=document.createElement("strong"),span=document.createElement("span"),button=document.createElement("button");strong.textContent="Let’s set up your AI";span.textContent="Choose a provider, model, and this PC’s encrypted API key to start desktop chat.";copy.append(strong,span);button.className="primary";button.textContent="Get started";button.onclick=()=>showView("settings");banner.append(copy,button);document.querySelector(".conversation").prepend(banner)}}
const usageCard=document.createElement("article");usageCard.className="usage-card";usageCard.innerHTML='<div><h2>Model usage</h2><p>Local estimates from requests sent by this PC. Provider billing remains authoritative.</p></div><div id="usage-summary" class="usage-summary"><div><strong>0</strong><span>Requests</span></div><div><strong>0</strong><span>Tokens</span></div><div><strong>$0.0000</strong><span>Estimated</span></div></div>';providerCard.after(usageCard);
async function loadUsage(){const rows=await window.junction.usage(),requests=rows.length,tokens=rows.reduce((n,x)=>n+x.inputTokens+x.outputTokens,0),usd=rows.reduce((n,x)=>n+x.estimatedUsd,0),boxes=usageCard.querySelectorAll("strong");boxes[0].textContent=String(requests);boxes[1].textContent=tokens.toLocaleString();boxes[2].textContent=`$${usd.toFixed(4)}`}
const memoryToolbar=document.createElement("div");memoryToolbar.className="memory-toolbar";const memorySearch=document.createElement("input"),memoryCount=document.createElement("span");memorySearch.placeholder="Search remembered facts";memoryCount.className="memory-count";memoryToolbar.append(memorySearch,memoryCount);product("memory-list").before(memoryToolbar);async function updateMemoryMeta(){const rows=await window.junction.memories();memoryCount.textContent=`${rows.length} / 200 facts`;const query=memorySearch.value.trim().toLowerCase();document.querySelectorAll(".memory-row").forEach(row=>row.hidden=query&&!row.textContent.toLowerCase().includes(query))}memorySearch.oninput=updateMemoryMeta;memoryCard.addEventListener("click",()=>setTimeout(updateMemoryMeta,50));
const feedView=product("view-feed"),feedBody=feedView.querySelector(".empty");feedBody.outerHTML='<div class="feed-toolbar"><button class="filter-chip active" data-feed-filter="all">All local</button><button class="filter-chip" data-feed-filter="success">Completed</button><button class="filter-chip" data-feed-filter="failure">Needs attention</button></div><div class="notice" style="margin:0 0 16px"><strong>Your Junction · local plus shared</strong><span>Local companion activity appears immediately. Signed-in shared Feed items are read-only and refresh only when you explicitly sync.</span></div><div id="feed-list" class="feed-list"><div class="skeleton"></div><div class="skeleton"></div></div>';
let feedFilter="all";async function loadFeed(){const rows=await window.junction.audit(),filtered=rows.filter(row=>feedFilter==="all"||(feedFilter==="success"?row.outcome==="success":row.outcome==="failure"));const list=product("feed-list");if(!filtered.length){list.innerHTML='<div class="empty-audit">No matching local activity.</div>';return}list.replaceChildren(...filtered.map(row=>{const card=document.createElement("article");card.className="feed-event";const icon=document.createElement("i");icon.textContent=row.outcome==="failure"?"!":"✓";const copy=document.createElement("div"),title=document.createElement("strong"),meta=document.createElement("span"),time=document.createElement("time");title.textContent=row.event==="proposal_created"?"Junction evaluated PC context":row.outcome==="failure"?"PC context needed attention":"PC context inspection completed";meta.textContent=`${row.capability||"Local policy"} · ${row.decision||"blocked"}`;time.textContent=new Date(row.timestamp).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"});copy.append(title,meta);card.append(icon,copy,time);return card}))}document.querySelectorAll("[data-feed-filter]").forEach(button=>button.onclick=()=>{feedFilter=button.dataset.feedFilter;document.querySelectorAll("[data-feed-filter]").forEach(x=>x.classList.toggle("active",x===button));loadFeed()});
const metrics=document.createElement("div");metrics.className="audit-metrics";document.querySelector("#view-audit .intro").after(metrics);async function loadMetrics(){const rows=await window.junction.audit(),completed=rows.filter(x=>x.outcome==="success").length,blocked=rows.filter(x=>x.decision==="blocked").length,failed=rows.filter(x=>x.outcome==="failure").length;metrics.innerHTML="";for(const [value,label] of [[rows.length,"Local decisions"],[completed,"Completed"],[blocked,"Blocked"],[failed,"Failed"]]){const card=document.createElement("div");card.className="metric-card";const strong=document.createElement("strong"),span=document.createElement("span");strong.textContent=value;span.textContent=label;card.append(strong,span);metrics.append(card)}}
document.querySelector('[data-view="feed"]').addEventListener("click",loadFeed);document.querySelector('[data-view="audit"]').addEventListener("click",loadMetrics);document.querySelector('[data-view="settings"]').addEventListener("click",()=>{loadCatalog();loadUsage();updateMemoryMeta()});product("send-message").addEventListener("click",()=>setTimeout(loadUsage,500));loadCatalog();loadUsage();updateMemoryMeta();loadFeed();loadMetrics();
