"use strict";
const el = id => document.getElementById(id);
let contextSnapshot = null;
function showView(name,{focusHeading=false}={}){document.querySelectorAll(".view").forEach(v=>{const active=v.id===`view-${name}`;v.classList.toggle("active",active);v.setAttribute("aria-hidden",String(!active))});document.querySelectorAll(".nav").forEach(n=>{const active=n.dataset.view===name;n.classList.toggle("active",active);n.setAttribute("aria-current",active?"page":"false")});if(name==="audit")loadAudit();if(focusHeading){const heading=document.querySelector(`#view-${name} h1`);heading?.setAttribute("tabindex","-1");heading?.focus()}}
document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll("[data-view-link]").forEach(b=>b.onclick=()=>showView(b.dataset.viewLink));showView("chat");
function message(id,text){const n=el(id);n.textContent=text;n.classList.add("show");setTimeout(()=>n.classList.remove("show"),5000)}
async function action(fn){el("error").classList.remove("show");try{await fn();await refresh()}catch(error){message("error",error.message)}}
async function refresh(){const s=await window.junction.status();el("device-name").textContent=s.device.name;el("device-id").textContent=s.device.deviceId;el("account").textContent=s.account?`${s.account.displayName||"Junction owner"} · ${s.account.email||s.account.uid}`:s.cloudConfigured?"Not signed in on this PC.":"Account linking is not configured in this build.";el("sign-in").classList.toggle("hidden",!!s.account);el("sign-in").disabled=!s.cloudConfigured;el("sign-out").classList.toggle("hidden",!s.account);el("sync").disabled=!s.account;el("sync").checked=s.device.syncEnabled;el("connection").textContent=s.device.syncEnabled?"Account linked":"Local only";el("connection-detail").textContent=s.device.syncEnabled?"Device registered · context stays local":"Nothing leaves this PC"}
async function refreshLocalBrain(){const s=await window.junction.localBrainStatus();el("local-brain-state").textContent=s.enabled?`Local Junction Brain ready (${s.model}). Create a one-time code to pair a phone.`:"Pair your phone directly with this PC. This uses Junction encryption and a free relay, not Google sign-in, a VPN, or an exposed model endpoint.";el("revoke-local-brain").classList.toggle("hidden",!s.enabled)}
async function loadAudit(){const list=el("audit-list");try{const rows=await window.junction.audit();if(!rows.length){list.innerHTML='<div class="empty-audit">No local companion decisions yet. Explicit context inspections will appear here.</div>';return}list.replaceChildren(...rows.map(row=>{const item=document.createElement("div");item.className="audit-row";const state=document.createElement("div");state.className="audit-state";state.textContent=row.outcome==="failure"?"!":"✓";const copy=document.createElement("div");copy.className="audit-copy";const title=document.createElement("strong");title.textContent=row.event==="proposal_created"?"Context inspection proposed":row.outcome==="failure"?"Context inspection failed":"Context inspection completed";const meta=document.createElement("span");meta.textContent=`${row.capability||"Local policy"} · ${row.decision||"blocked"}${row.reason?` · ${row.reason}`:""}`;copy.append(title,meta);const time=document.createElement("span");time.className="audit-time";time.textContent=new Date(row.timestamp).toLocaleString();item.append(state,copy,time);return item}))}catch{list.textContent="Local audit could not be read."}}
el("sign-in").onclick=()=>action(()=>window.junction.signIn());el("sign-out").onclick=()=>action(()=>window.junction.signOut());el("sync").onchange=e=>action(()=>window.junction.setSync(e.target.checked));
const localBrainCard=document.createElement("article");localBrainCard.innerHTML='<div><h2>Local Junction Brain</h2><p id="local-brain-state"></p><img id="local-brain-qr" class="hidden" alt="Scan this QR code in Junction on your phone"><details id="local-brain-manual" class="hidden"><summary>Use a pairing code instead</summary><code id="local-brain-code"></code></details></div><div><button id="pair-local-brain" class="primary">Show phone QR code</button><button id="revoke-local-brain" class="secondary hidden">Revoke paired phones</button></div>';document.querySelector(".settings")?.insertBefore(localBrainCard,document.querySelector(".provider-card"));el("pair-local-brain").onclick=()=>action(async()=>{const pair=await window.junction.localBrainPair(),qr=el("local-brain-qr");qr.src=pair.qrDataUrl;qr.classList.remove("hidden");el("local-brain-code").textContent=`Expires ${new Date(pair.expiresAt).toLocaleTimeString()}: ${pair.code}`;el("local-brain-manual").classList.remove("hidden");await refreshLocalBrain()});el("revoke-local-brain").onclick=()=>action(async()=>{await window.junction.revokeLocalBrain();el("local-brain-qr").classList.add("hidden");el("local-brain-manual").classList.add("hidden");await refreshLocalBrain()});refreshLocalBrain();
el("open-mafioso").onclick=()=>action(async()=>{const result=await window.junction.openMafioso();message("toast",result.kind==="url"?"Opening hosted Mafioso…":"Opening the local Mafioso project…")});
el("inspect").onclick=()=>action(async()=>{el("inspect").disabled=true;el("context-summary").textContent="Reading Windows accessibility metadata…";try{contextSnapshot=await window.junction.inspect();const count=Array.isArray(contextSnapshot.elements)?contextSnapshot.elements.length:0;el("context-summary").classList.remove("muted-box");el("context-summary").textContent=`${contextSnapshot.window?.title||"Foreground app"} · ${count} labelled elements · UNTRUSTED local context`;el("result").textContent=JSON.stringify(contextSnapshot,null,2);el("context-details").classList.remove("hidden");el("context-chip").classList.remove("hidden");message("toast","Local context collected. It has not been sent anywhere.");await loadAudit()}finally{el("inspect").disabled=false}});
el("clear-context").onclick=()=>{contextSnapshot=null;el("context-chip").classList.add("hidden");el("context-details").classList.add("hidden");el("result").textContent="";el("context-summary").textContent="No context collected this session.";el("context-summary").classList.add("muted-box")};refresh();
